
project_id = "blmuvicbfduadqsrarhn"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[inbucket]
enabled = true

[analytics]
enabled = false

[experimental.functions.deploy.config]
node_version = "18"

[functions.monthsary-reminder]
verify_jwt = false

[auth]
enabled = true
site_url = "http://localhost:3000"